sudo: required
language: r
r:
    - 3.6.3
r_binary_packages:
    - Rcpp
    - devtools
    - knitr
    - testthat
cache: packages
os:
    - linux
    - osx
dist: xenial
addons:
  apt:
    packages: libmpfr-dev
  homebrew:
    packages: mpfr
