sudo: required
language: r
r:
    - 3.6.3
r_binary_packages:
    - Rcpp
    - devtools
    - knitr
    - testthat
cache: packages
os:
    - linux
    - osx
osx_image: xcode13.2
addons:
  apt:
    packages: libmpfr-dev
  homebrew:
    packages: mpfr
jobs:
  allow_failures:
    - os: osx
