sudo: required
language: r
r_binary_packages:
    - Rcpp
    - devtools
    - knitr
    - testthat
cache: packages
os:
    - linux
    - osx
dist: xenial
before_install:
    - sudo apt-get install -qy libmpfr-dev
addons:
  apt:
    packages: libmpfr-dev
  homebrew:
    packages: mpfr
