// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// kummer_gsl
NumericVector kummer_gsl(NumericVector x, double a, double b, int lnchf);
RcppExport SEXP mpb2_kummer_gsl(SEXP xSEXP, SEXP aSEXP, SEXP bSEXP, SEXP lnchfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type lnchf(lnchfSEXP);
    rcpp_result_gen = Rcpp::wrap(kummer_gsl(x, a, b, lnchf));
    return rcpp_result_gen;
END_RCPP
}
// dmpb
NumericVector dmpb(IntegerVector x, NumericVector alpha, NumericVector beta, NumericVector c);
RcppExport SEXP mpb2_dmpb(SEXP xSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(dmpb(x, alpha, beta, c));
    return rcpp_result_gen;
END_RCPP
}
// pmpb
NumericVector pmpb(IntegerVector q, NumericVector alpha, NumericVector beta, NumericVector c);
RcppExport SEXP mpb2_pmpb(SEXP qSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(pmpb(q, alpha, beta, c));
    return rcpp_result_gen;
END_RCPP
}
// rmpb
IntegerVector rmpb(int n, NumericVector alpha, NumericVector beta, NumericVector c);
RcppExport SEXP mpb2_rmpb(SEXP nSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(rmpb(n, alpha, beta, c));
    return rcpp_result_gen;
END_RCPP
}
