# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Kummer function for real values
#' @param x vector of parameters
#' @param a floating point parameter
#' @param b floating point parameter
#' @param lnchf 0 or 1; if 1, the log of the value is returned
#' @name kummer
#' @rdname kummer
#' @export
kummer_gsl <- function(x, a, b, lnchf = 0L) {
    .Call('mpb2_kummer_gsl', PACKAGE = 'mpb2', x, a, b, lnchf)
}

cpp_dmpb <- function(x, alpha, beta, c, log_p = FALSE) {
    .Call('mpb2_cpp_dmpb', PACKAGE = 'mpb2', x, alpha, beta, c, log_p)
}

cpp_pmpb <- function(q, alpha, beta, c, lower_tail, log_p) {
    .Call('mpb2_cpp_pmpb', PACKAGE = 'mpb2', q, alpha, beta, c, lower_tail, log_p)
}

cpp_rmpb <- function(n, alpha, beta, c) {
    .Call('mpb2_cpp_rmpb', PACKAGE = 'mpb2', n, alpha, beta, c)
}

cpp_qmpb <- function(p, alpha, beta, c, lower_tail, log_p) {
    .Call('mpb2_cpp_qmpb', PACKAGE = 'mpb2', p, alpha, beta, c, lower_tail, log_p)
}

