# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gillespie Algorithm for the poisson-beta
#'
#' Gillespie Algorithm to simulate from basic kinetic model of gene activation and mRNA transcription
#' @param n number of simulations
#' @param r_act polymerase binding rate / DNA activation rate
#' @param r_deact polymerase unbinding rate / DNA deactivation rate
#' @param r_on transcription rate
#' @param r_degr mRNA degradation rate
#' @name gmRNA
#' @rdname gmRNA
#' @export
gmRNA_switch <- function(n, r_act, r_deact, r_on, r_degr) {
    .Call('mpb2_gmRNA_switch', PACKAGE = 'mpb2', n, r_act, r_deact, r_on, r_degr)
}

#' @rdname gmRNA
#' @export
gmRNA_burst <- function(n, r_burst, s_burst, r_degr) {
    .Call('mpb2_gmRNA_burst', PACKAGE = 'mpb2', n, r_burst, s_burst, r_degr)
}

#' @rdname gmRNA
#' @export
gmRNA_basic <- function(n, r_on, r_degr) {
    .Call('mpb2_gmRNA_basic', PACKAGE = 'mpb2', n, r_on, r_degr)
}

#' Kummer's (confluent hypergeometric) function
#'
#' Kummer's (confluent hypergeometric) function of the first kind
#' for numeric (non-complex) values and input parameters
#' @param x numeric value or vector
#' @param a,b numeric parameters of the Kummer function
#' @name chf_1F1
#' @rdname chf_1F1
#' @export
chf_1F1 <- function(x, a, b) {
    .Call('mpb2_chf_1F1', PACKAGE = 'mpb2', x, a, b)
}

cpp_dmpb <- function(x, alpha, beta, c, log_p = FALSE) {
    .Call('mpb2_cpp_dmpb', PACKAGE = 'mpb2', x, alpha, beta, c, log_p)
}

cpp_pmpb <- function(q, alpha, beta, c, lower_tail, log_p) {
    .Call('mpb2_cpp_pmpb', PACKAGE = 'mpb2', q, alpha, beta, c, lower_tail, log_p)
}

cpp_rmpb <- function(n, alpha, beta, c) {
    .Call('mpb2_cpp_rmpb', PACKAGE = 'mpb2', n, alpha, beta, c)
}

cpp_qmpb <- function(p, alpha, beta, c, lower_tail, log_p) {
    .Call('mpb2_cpp_qmpb', PACKAGE = 'mpb2', p, alpha, beta, c, lower_tail, log_p)
}

